"""empty message

Revision ID: 08f9efacd776
Revises: 23289af83888
Create Date: 2019-05-03 09:42:34.418722

"""

# revision identifiers, used by Alembic.
revision = '08f9efacd776'
down_revision = '23289af83888'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
