"""empty message

Revision ID: 14b1dd5f4bfc
Revises: 12c6128bcd85
Create Date: 2019-05-03 23:12:06.657044

"""

# revision identifiers, used by Alembic.
revision = '14b1dd5f4bfc'
down_revision = '12c6128bcd85'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('images', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'images')
    # ### end Alembic commands ###
