"""empty message

Revision ID: 2a1b5a851e70
Revises: 08f9efacd776
Create Date: 2019-05-03 10:25:05.935334

"""

# revision identifiers, used by Alembic.
revision = '2a1b5a851e70'
down_revision = '08f9efacd776'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
