"""empty message

Revision ID: 3de4f1ab2917
Revises: 2a1b5a851e70
Create Date: 2019-05-03 17:41:10.470255

"""

# revision identifiers, used by Alembic.
revision = '3de4f1ab2917'
down_revision = '2a1b5a851e70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('url', sa.String(), nullable=True))
    op.add_column('images', sa.Column('width', sa.Float(), nullable=True))
    op.drop_column('images', 'image_url')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('images', 'width')
    op.drop_column('images', 'url')
    op.drop_column('images', 'height')
    # ### end Alembic commands ###
