"""empty message

Revision ID: ff0cdd1acf00
Revises: 6c117e662821
Create Date: 2019-05-22 12:57:45.318880

"""

# revision identifiers, used by Alembic.
revision = 'ff0cdd1acf00'
down_revision = '6c117e662821'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'score')
    # ### end Alembic commands ###
